# Generated by Django 4.2.8 on 2024-05-21 02:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/profile.jpg', upload_to='profile/images'),
        ),
    ]
