# Generated by Django 4.2.8 on 2024-05-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
